export const PROJECTS = [
  "EAH - Geliştirme - SAP CX Commerce Hybris",
  "İGA - Geliştirme - SAP CX Commerce Hybris",
  "WARMHAUS - Geliştirme - SAP CX Commerce Hybris",
  "Avansas - Geliştirme - SAP CX Commerce",
  "enoca - ARGE - EvoSuggest - SAP CX Commerce  - Geliştirme",
  "Sanko Commerce",
  "SHARJAH - Geliştirme - SAP CX Commerce Cloud Hybris",
  "TEKNOSA - Geliştirme - SAP CX Commerce Hybris",
  "EBEBEK - Geliştirme - SAP CX Commerce Hybris",
  "GRATİS - Danışmanlık - SAP CX Commerce Hybris",
  "HASÇELİK - Geliştirme - SAP CX Commerce Hybris",
  "İPRAGAZ - Geliştirme - SAP CX Commerce Hybris",
  "CARREFOURSA - Geliştirme - SAP CX Commerce Hybris",
  "KARACA - Europe - Geliştirme - SAP CX Commerce Hybris",
  "Kızılay - Geliştirme - SAP CX Commerce Hybris",
  "COMMERCE_LAB - Geliştirme - .NET",
  "KOCAER - Kurumsal Web - Geliştirme - SAP CX Commerce Hybris",
  "MAVİ - Geliştirme - SAP CX Commerce Hybris",
  "MİLANGAZ - Geliştirme - SAP CX Commerce Hybris",
  "Avansas UK - SAP CX Commerce - Geliştirme",
  "CARREFOURSA - Geliştirme - SAP CX Commerce Hybris - PERFORMANS",
  "enoca - FİNANS ve MUHASEBE",
  "enoca - İNSAN KAYNAKLARI",
  "enoca - SÜREÇ YÖNETİMİ ve İDARİ İŞLER",
  "enoca - WEB - enoca.com (yeni)",
  "enoca - WEB - BLOG",
  "enoca - İNSAN KAYNAKLARI - Gelişim",
  "enoca - ARGE - DanaBul - .NET - Geliştirme",
  "Enoca",
  "enoca - AKADEMİ - Eğitim - SAP ERP",
  "enoca - AKADEMİ - Eğitim - SAP COMMERCE - FRONTEND",
  "enoca - AKADEMİ - Eğitim - SAP COMMERCE - BACKEND",
  "GRATİS - Kariyer - Geliştirme - SAP CX Commerce Hybris",
  "enoca - AKADEMİ - Kişisel Gelişim - SAP COMMERCE - BACKEND",
  "enoca - AKADEMİ - Eğitim - Analist",
  "BALSU - Geliştirme - SAP ERP",
  "Hasçelik PPDS",
  "HASÇELİK - Geliştirme - SAP ERP",
  "MaaS",
  "NEC AYNA"
] as const; 